create table companies (id bigint not null auto_increment, company_location varchar(255) not null, company_name varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table evaluations (effectiveness integer not null, efficiency integer not null, facilities integer not null, guidance integer not null, id integer not null auto_increment, motivation integer not null, traineeship_position_id integer, evaluation_type enum ('COMPANY_EVALUATION','PROFESSOR_EVALUATION'), primary key (id)) engine=InnoDB;
create table professor_interests (professor_id bigint not null, interest varchar(255)) engine=InnoDB;
create table professors (id bigint not null auto_increment, professor_name varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table student_interests (student_id bigint not null, interest varchar(255)) engine=InnoDB;
create table student_skills (student_id bigint not null, skill varchar(255)) engine=InnoDB;
create table students (avg_grade float(53) not null, looking_for_traineeship bit, id bigint not null auto_increment, am varchar(255) not null, preferred_location varchar(255), student_name varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table traineeship_positions (from_date date, id integer not null auto_increment, is_assigned bit not null, pass_fail_grade bit not null, to_date date, company_id bigint, professor_id bigint, student_id bigint, description TEXT, skills varchar(255), student_logbook varchar(255), title varchar(255) not null, topics varchar(255), primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, password varchar(255) not null, username varchar(255) not null, role enum ('COMPANY','PROFESSOR','STUDENT','TRAINEESHIP_COMMITTEE') not null, primary key (id)) engine=InnoDB;
alter table companies add constraint UKp8h4uk1wt76vxswx52knyf1nr unique (username);
alter table professors add constraint UK8pcx6lfwce305oxmjuobv2dhk unique (username);
alter table students add constraint UKh3nmnsffgpfn2dk8ilfwq81bn unique (am);
alter table students add constraint UKakwqgcdnid3qo41cqpdu4ke01 unique (username);
alter table traineeship_positions add constraint UKtpfh1cx4n4mkkfukjh9grjqix unique (student_id);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table evaluations add constraint FKjfg2ljdel0aag3eeavkhfylx4 foreign key (traineeship_position_id) references traineeship_positions (id);
alter table professor_interests add constraint FKewbbmh0vpfh77fddlpq57slkr foreign key (professor_id) references professors (id);
alter table student_interests add constraint FKgoxm9l5vebp18b82s5ucooo09 foreign key (student_id) references students (id);
alter table student_skills add constraint FKovs9ju1ccjg7kq2m3tct9oh1y foreign key (student_id) references students (id);
alter table traineeship_positions add constraint FK8ftvvlbpokdox2gssd2pb8xg7 foreign key (company_id) references companies (id);
alter table traineeship_positions add constraint FKkq36ou0s44n331aro3y7rljxg foreign key (student_id) references students (id);
alter table traineeship_positions add constraint FK3p5adkokgdioixdo3mrci5tol foreign key (professor_id) references professors (id);
